name = "BuildersRefuge"
author = "BuildersRefuge"
version = "1.20"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2142b6910da7e86b19174f6f022c2496933ddad56444a9b469728b1a3e61e976"

[versions]
fabric = "0.16.9"
minecraft = "1.20.4"
