name = "BuildersRefuge"
author = "BuildersRefuge"
version = "1.20"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ae8cd9d74d42ebb3afab7255ad07e2c2a782854829213564907011fbfdc86f27"

[versions]
fabric = "0.16.5"
minecraft = "1.20.4"
