name = "BuildersRefuge"
author = "BuildersRefuge"
version = "1.20"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d3895e2fb65523cfc846454a1bc1d3a2b6e4ad061be63e898d602582305e6b4"

[versions]
fabric = "0.16.9"
minecraft = "1.20.4"
