name = "BuildersRefuge"
author = "BuildersRefuge"
version = "1.20-v1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4ef500260324b130f7b355b6c81a0c6df2309f7ecbd7402dcdcb3fd29a8a8847"

[versions]
fabric = "0.14.24"
minecraft = "1.20.2"
