name = "BuildersRefuge"
author = "BuildersRefuge"
version = "1.20"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2832f7e0770a3d4840758e466eb0312087827f749a6a0a04b0cf5e982b7a1346"

[versions]
fabric = "0.16.5"
minecraft = "1.20.4"
