name: Modpack
on: [push, pull_request]

jobs:
  packwiz:
    name: Setup packwiz
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 'stable'

    - name: Checkout packwiz
      uses: actions/checkout@v1
      with:
        repository: packwiz/packwiz
        ref: refs/heads/main
        path: packwiz

    - name: Build packwiz
      run: go build -C ../packwiz-repo

    - name: Checkout
      uses: actions/checkout@v1

    - name: Export modpack
      run: ../packwiz/packwiz modrinth export

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        path: '*.mrpack'
